- name: Configurer des interfaces OPNsense
  hosts: opnsense
  gather_facts: no



  tasks:
    - name: Configurer l'interface
      uri:
        url: "https://{{ opnsense_host }}/api/interfaces/{{ item.name }}/setInterface"
        method: POST
        user: "{{ api_user }}"
        password: "{{ api_password }}"
        body_format: json
        body:
          descr: "{{ item.descr }}"
          enable: true
          ipv4addr: "{{ item.ip }}"
          subnet: "{{ item.subnet }}"
          apply: true
        validate_certs: no
      loop: "{{ interfaces }}"

    - name: Afficher le résultat de la dernière config
      debug:
        var: result