- name: Configuration des vlan sur eth0
  hosts: Vyos
  gather_facts: no
  collections: 
    - vyos.vyos

  tasks: 

    - name: Creation du {{ item.id }}
      vyos.vyos.vyos_interface:
        id: {{ item.id }}
        

  