- name: Creation du serveur DHCP
  hosts: Vyos
  gather_facts: no 
  collections: 
    - vyos.vyos

  tasks: 

    - name: Creation DHCP Vlan 10
      vyos.vyos.vyos_dhcp_server:
        name: VLAN10
        subnet: 192.168.10.0/16
        start: 192.168.10.10
        stop: 192.168.10.200
        default_router: 192.168.10.1
        dns_server: 8.8.8.8

    - name: Creation DHCP Vlan 20
      vyos.vyos.vyos_dhcp_server:
        name: VLAN20
        subnet: 192.168.20.0/16
        start: 192.168.20.10
        stop: 192.168.20.200
        default_router: 192.168.20.1
        dns_server: 8.8.8.8

    - name: Sauvegarder les changements
      vyos.vyos.vyos_system:
        state: saved
