- name: Config VyOS
  hosts: vyos
  gather_facts: no
  roles:
    - vyos_interfaces
    - vyos_vlans
    - vyos_dhcp

- name: Config OPNsense
  hosts: opnsense
  gather_facts: no
  roles:
    - opnsense_interfaces