- name: Configurer les interfaces OPNsense via l'API
  uri:
    url: "https://{{ inventory_hostname }}/api/interfaces/{{ item.name }}/setInterface"
    method: POST
    user: "{{ ansible_user }}"
    password: "{{ ansible_password }}"
    body_format: json
    body:
      enable: true
      address: "{{ item.address }}"
      subnet: "{{ item.subnet }}"
      apply: true
    validate_certs: no
    force_basic_auth: yes
    status_code: 200
  loop: "{{ interfaces }}"