all:
  hosts:  
    vyos:
      ansible_host: 192.168.7.5
      ansible_user: vyos 
      ansible_password: vyos 
      ansible_network_os: vyos 
      ansible_connection: ssh


    opnsense:
      ansible_host: 192.168.7.1
      ansible_user: root 
      ansible_password: opnsense 
      ansible_network_os: opnsense
      ansible_connection: ssh